import geohash
from hashids import Hashids
from addok.config import config


hashids = Hashids()


cacodeDict = {
  "A01": { "edist":"Central & Western District", "cdist":"中西區", "earea":"Chung Wan", "carea":"中環"},
  "A02": { "edist":"Central & Western District", "cdist":"中西區", "earea":"Mid Levels East", "carea":"半山東"},
  "A03": { "edist":"Central & Western District", "cdist":"中西區", "earea":"Castle Road", "carea":"衛城"},
  "A04": { "edist":"Central & Western District", "cdist":"中西區", "earea":"Peak", "carea":"山頂"},
  "A05": { "edist":"Central & Western District", "cdist":"中西區", "earea":"University", "carea":"大學"},
  "A06": { "edist":"Central & Western District", "cdist":"中西區", "earea":"Kwun Lung", "carea":"觀龍"},
  "A07": { "edist":"Central & Western District", "cdist":"中西區", "earea":"Kennedy Town & Mount Davis", "carea":"堅摩"},
  "A08": { "edist":"Central & Western District", "cdist":"中西區", "earea":"Sai Wan", "carea":"西環"},
  "A09": { "edist":"Central & Western District", "cdist":"中西區", "earea":"Belcher", "carea":"寶翠"},
  "A10": { "edist":"Central & Western District", "cdist":"中西區", "earea":"Shek Tong Tsui", "carea":"石塘咀"},
  "A11": { "edist":"Central & Western District", "cdist":"中西區", "earea":"Sai Ying Pun", "carea":"西營盤"},
  "A12": { "edist":"Central & Western District", "cdist":"中西區", "earea":"Sheung Wan", "carea":"上環"},
  "A13": { "edist":"Central & Western District", "cdist":"中西區", "earea":"Tung Wah", "carea":"東華"},
  "A14": { "edist":"Central & Western District", "cdist":"中西區", "earea":"Centre Street", "carea":"正街"},
  "A15": { "edist":"Central & Western District", "cdist":"中西區", "earea":"Water Street", "carea":"水街"},
  "B01": { "edist":"Wan Chai District", "cdist":"灣仔區", "earea":"Hennessy", "carea":"軒尼詩"},
  "B02": { "edist":"Wan Chai District", "cdist":"灣仔區", "earea":"Oi Kwan", "carea":"愛群"},
  "B03": { "edist":"Wan Chai District", "cdist":"灣仔區", "earea":"Canal Road", "carea":"鵝頸"},
  "B04": { "edist":"Wan Chai District", "cdist":"灣仔區", "earea":"Causeway Bay", "carea":"銅鑼灣"},
  "B05": { "edist":"Wan Chai District", "cdist":"灣仔區", "earea":"Victoria Park", "carea":"維園"},
  "B06": { "edist":"Wan Chai District", "cdist":"灣仔區", "earea":"Tin Hau", "carea":"天后"},
  "B07": { "edist":"Wan Chai District", "cdist":"灣仔區", "earea":"Tai Hang", "carea":"大坑"},
  "B08": { "edist":"Wan Chai District", "cdist":"灣仔區", "earea":"Jardine's Lookout", "carea":"渣甸山"},
  "B09": { "edist":"Wan Chai District", "cdist":"灣仔區", "earea":"Broadwood", "carea":"樂活"},
  "B10": { "edist":"Wan Chai District", "cdist":"灣仔區", "earea":"Happy Valley", "carea":"跑馬地"},
  "B11": { "edist":"Wan Chai District", "cdist":"灣仔區", "earea":"Stubbs Road", "carea":"司徒拔道"},
  "B12": { "edist":"Wan Chai District", "cdist":"灣仔區", "earea":"Southorn", "carea":"修頓"},
  "B13": { "edist":"Wan Chai District", "cdist":"灣仔區", "earea":"Tai Fat Hau", "carea":"大佛口"},
  "C01": { "edist":"Eastern District", "cdist":"東區", "earea":"Tai Koo Shing West", "carea":"太古城西"},
  "C02": { "edist":"Eastern District", "cdist":"東區", "earea":"Tai Koo Shing East", "carea":"太古城東"},
  "C03": { "edist":"Eastern District", "cdist":"東區", "earea":"Lei King Wan", "carea":"鯉景灣"},
  "C04": { "edist":"Eastern District", "cdist":"東區", "earea":"Sai Wan Ho", "carea":"西灣河"},
  "C05": { "edist":"Eastern District", "cdist":"東區", "earea":"Aldrich Bay", "carea":"愛秩序灣"},
  "C06": { "edist":"Eastern District", "cdist":"東區", "earea":"Shaukeiwan", "carea":"筲箕灣"},
  "C07": { "edist":"Eastern District", "cdist":"東區", "earea":"A Kung Ngam", "carea":"阿公岩"},
  "C08": { "edist":"Eastern District", "cdist":"東區", "earea":"Heng Fa Chuen", "carea":"杏花邨"},
  "C09": { "edist":"Eastern District", "cdist":"東區", "earea":"Tsui Wan", "carea":"翠灣"},
  "C10": { "edist":"Eastern District", "cdist":"東區", "earea":"Yan Lam", "carea":"欣藍"},
  "C11": { "edist":"Eastern District", "cdist":"東區", "earea":"Siu Sai Wan", "carea":"小西灣"},
  "C12": { "edist":"Eastern District", "cdist":"東區", "earea":"King Yee", "carea":"景怡"},
  "C13": { "edist":"Eastern District", "cdist":"東區", "earea":"Wan Tsui", "carea":"環翠"},
  "C14": { "edist":"Eastern District", "cdist":"東區", "earea":"Fei Tsui", "carea":"翡翠"},
  "C15": { "edist":"Eastern District", "cdist":"東區", "earea":"Mount Parker", "carea":"柏架山"},
  "C16": { "edist":"Eastern District", "cdist":"東區", "earea":"Braemar Hill", "carea":"寶馬山"},
  "C17": { "edist":"Eastern District", "cdist":"東區", "earea":"Fortress Hill", "carea":"炮台山"},
  "C18": { "edist":"Eastern District", "cdist":"東區", "earea":"City Garden", "carea":"城市花園"},
  "C19": { "edist":"Eastern District", "cdist":"東區", "earea":"Provident", "carea":"和富"},
  "C20": { "edist":"Eastern District", "cdist":"東區", "earea":"Fort Street", "carea":"堡壘"},
  "C21": { "edist":"Eastern District", "cdist":"東區", "earea":"Kam Ping", "carea":"錦屏"},
  "C22": { "edist":"Eastern District", "cdist":"東區", "earea":"Tanner", "carea":"丹拿"},
  "C23": { "edist":"Eastern District", "cdist":"東區", "earea":"Healthy Village", "carea":"健康村"},
  "C24": { "edist":"Eastern District", "cdist":"東區", "earea":"Quarry Bay", "carea":"鰂魚涌"},
  "C25": { "edist":"Eastern District", "cdist":"東區", "earea":"Nam Fung", "carea":"南豐"},
  "C26": { "edist":"Eastern District", "cdist":"東區", "earea":"Kornhill", "carea":"康怡"},
  "C27": { "edist":"Eastern District", "cdist":"東區", "earea":"Kornhill Garden", "carea":"康山"},
  "C28": { "edist":"Eastern District", "cdist":"東區", "earea":"Hing Tung", "carea":"興東"},
  "C29": { "edist":"Eastern District", "cdist":"東區", "earea":"Lower Yiu Tung", "carea":"下耀東"},
  "C30": { "edist":"Eastern District", "cdist":"東區", "earea":"Upper Yiu Tung", "carea":"上耀東"},
  "C31": { "edist":"Eastern District", "cdist":"東區", "earea":"Hing Man", "carea":"興民"},
  "C32": { "edist":"Eastern District", "cdist":"東區", "earea":"Lok Hong", "carea":"樂康"},
  "C33": { "edist":"Eastern District", "cdist":"東區", "earea":"Tsui Tak", "carea":"翠德"},
  "C34": { "edist":"Eastern District", "cdist":"東區", "earea":"Yue Wan", "carea":"漁灣"},
  "C35": { "edist":"Eastern District", "cdist":"東區", "earea":"Kai Hiu", "carea":"佳曉"},
  "D01": { "edist":"Southern District", "cdist":"南區", "earea":"Aberdeen", "carea":"香港仔"},
  "D02": { "edist":"Southern District", "cdist":"南區", "earea":"Ap Lei Chau Estate", "carea":"鴨脷洲邨"},
  "D03": { "edist":"Southern District", "cdist":"南區", "earea":"Ap Lei Chau North", "carea":"鴨脷洲北"},
  "D04": { "edist":"Southern District", "cdist":"南區", "earea":"Lei Tung I", "carea":"利東一"},
  "D05": { "edist":"Southern District", "cdist":"南區", "earea":"Lei Tung II", "carea":"利東二"},
  "D06": { "edist":"Southern District", "cdist":"南區", "earea":"South Horizons East", "carea":"海怡東"},
  "D07": { "edist":"Southern District", "cdist":"南區", "earea":"South Horizons West", "carea":"海怡西"},
  "D08": { "edist":"Southern District", "cdist":"南區", "earea":"Wah Kwai", "carea":"華貴"},
  "D09": { "edist":"Southern District", "cdist":"南區", "earea":"Wah Fu South", "carea":"華富南"},
  "D10": { "edist":"Southern District", "cdist":"南區", "earea":"Wah Fu North", "carea":"華富北"},
  "D11": { "edist":"Southern District", "cdist":"南區", "earea":"Pokfulam", "carea":"薄扶林"},
  "D12": { "edist":"Southern District", "cdist":"南區", "earea":"Chi Fu", "carea":"置富"},
  "D13": { "edist":"Southern District", "cdist":"南區", "earea":"Tin Wan", "carea":"田灣"},
  "D14": { "edist":"Southern District", "cdist":"南區", "earea":"Shek Yue", "carea":"石漁"},
  "D15": { "edist":"Southern District", "cdist":"南區", "earea":"Wong Chuk Hang", "carea":"黃竹坑"},
  "D16": { "edist":"Southern District", "cdist":"南區", "earea":"Bays Area", "carea":"海灣"},
  "D17": { "edist":"Southern District", "cdist":"南區", "earea":"Stanley & Shek O", "carea":"赤柱及石澳"},
  "E01": { "edist":"Yau Tsim Mong District", "cdist":"油尖旺區", "earea":"Tsim Sha Tsui West", "carea":"尖沙咀西"},
  "E02": { "edist":"Yau Tsim Mong District", "cdist":"油尖旺區", "earea":"Kowloon Station", "carea":"九龍站"},
  "E03": { "edist":"Yau Tsim Mong District", "cdist":"油尖旺區", "earea":"Jordan West", "carea":"佐敦西"},
  "E04": { "edist":"Yau Tsim Mong District", "cdist":"油尖旺區", "earea":"Yau Ma Tei South", "carea":"油麻地南"},
  "E05": { "edist":"Yau Tsim Mong District", "cdist":"油尖旺區", "earea":"Charming", "carea":"富榮"},
  "E06": { "edist":"Yau Tsim Mong District", "cdist":"油尖旺區", "earea":"Mong Kok West", "carea":"旺角西"},
  "E07": { "edist":"Yau Tsim Mong District", "cdist":"油尖旺區", "earea":"Fu Pak", "carea":"富柏"},
  "E08": { "edist":"Yau Tsim Mong District", "cdist":"油尖旺區", "earea":"Olympic", "carea":"奧運"},
  "E09": { "edist":"Yau Tsim Mong District", "cdist":"油尖旺區", "earea":"Cherry", "carea":"櫻桃"},
  "E10": { "edist":"Yau Tsim Mong District", "cdist":"油尖旺區", "earea":"Tai Kok Tsui South", "carea":"大角咀南"},
  "E11": { "edist":"Yau Tsim Mong District", "cdist":"油尖旺區", "earea":"Tai Kok Tsui North", "carea":"大角咀北"},
  "E12": { "edist":"Yau Tsim Mong District", "cdist":"油尖旺區", "earea":"Tai Nan", "carea":"大南"},
  "E13": { "edist":"Yau Tsim Mong District", "cdist":"油尖旺區", "earea":"Mong Kok North", "carea":"旺角北"},
  "E14": { "edist":"Yau Tsim Mong District", "cdist":"油尖旺區", "earea":"Mong Kok East", "carea":"旺角東"},
  "E15": { "edist":"Yau Tsim Mong District", "cdist":"油尖旺區", "earea":"Mong Kok South", "carea":"旺角南"},
  "E16": { "edist":"Yau Tsim Mong District", "cdist":"油尖旺區", "earea":"Yau Ma Tei North", "carea":"油麻地北"},
  "E17": { "edist":"Yau Tsim Mong District", "cdist":"油尖旺區", "earea":"East Tsim Sha Tsui & King's Park", "carea":"尖東及京士柏"},
  "E18": { "edist":"Yau Tsim Mong District", "cdist":"油尖旺區", "earea":"Jordan North", "carea":"佐敦北"},
  "E19": { "edist":"Yau Tsim Mong District", "cdist":"油尖旺區", "earea":"Jordan South", "carea":"佐敦南"},
  "E20": { "edist":"Yau Tsim Mong District", "cdist":"油尖旺區", "earea":"Tsim Sha Tsui Central", "carea":"尖沙咀中"},
  "F01": { "edist":"Sham Shui Po District", "cdist":"深水埗區", "earea":"Po Lai", "carea":"寶麗"},
  "F02": { "edist":"Sham Shui Po District", "cdist":"深水埗區", "earea":"Cheung Sha Wan", "carea":"長沙灣"},
  "F03": { "edist":"Sham Shui Po District", "cdist":"深水埗區", "earea":"Nam Cheong North", "carea":"南昌北"},
  "F04": { "edist":"Sham Shui Po District", "cdist":"深水埗區", "earea":"Shek Kip Mei", "carea":"石硤尾"},
  "F05": { "edist":"Sham Shui Po District", "cdist":"深水埗區", "earea":"Nam Cheong East", "carea":"南昌東"},
  "F06": { "edist":"Sham Shui Po District", "cdist":"深水埗區", "earea":"Nam Cheong South", "carea":"南昌南"},
  "F07": { "edist":"Sham Shui Po District", "cdist":"深水埗區", "earea":"Nam Cheong Central", "carea":"南昌中"},
  "F08": { "edist":"Sham Shui Po District", "cdist":"深水埗區", "earea":"Nam Cheong West", "carea":"南昌西"},
  "F09": { "edist":"Sham Shui Po District", "cdist":"深水埗區", "earea":"Fu Cheong", "carea":"富昌"},
  "F10": { "edist":"Sham Shui Po District", "cdist":"深水埗區", "earea":"Lai Kok", "carea":"麗閣"},
  "F11": { "edist":"Sham Shui Po District", "cdist":"深水埗區", "earea":"Fortune", "carea":"幸福"},
  "F12": { "edist":"Sham Shui Po District", "cdist":"深水埗區", "earea":"Pik Wui", "carea":"碧匯"},
  "F13": { "edist":"Sham Shui Po District", "cdist":"深水埗區", "earea":"Lai Chi Kok Central", "carea":"荔枝角中"},
  "F14": { "edist":"Sham Shui Po District", "cdist":"深水埗區", "earea":"Lai Chi Kok South", "carea":"荔枝角南"},
  "F15": { "edist":"Sham Shui Po District", "cdist":"深水埗區", "earea":"Mei Foo South", "carea":"美孚南"},
  "F16": { "edist":"Sham Shui Po District", "cdist":"深水埗區", "earea":"Mei Foo Central", "carea":"美孚中"},
  "F17": { "edist":"Sham Shui Po District", "cdist":"深水埗區", "earea":"Mei Foo North", "carea":"美孚北"},
  "F18": { "edist":"Sham Shui Po District", "cdist":"深水埗區", "earea":"Lai Chi Kok North", "carea":"荔枝角北"},
  "F19": { "edist":"Sham Shui Po District", "cdist":"深水埗區", "earea":"Un Chau", "carea":"元州"},
  "F20": { "edist":"Sham Shui Po District", "cdist":"深水埗區", "earea":"So Uk", "carea":"蘇屋"},
  "F21": { "edist":"Sham Shui Po District", "cdist":"深水埗區", "earea":"Lei Cheng Uk", "carea":"李鄭屋"},
  "F22": { "edist":"Sham Shui Po District", "cdist":"深水埗區", "earea":"Lung Ping & Sheung Pak Tin", "carea":"龍坪及上白田"},
  "F23": { "edist":"Sham Shui Po District", "cdist":"深水埗區", "earea":"Ha Pak Tin", "carea":"下白田"},
  "F24": { "edist":"Sham Shui Po District", "cdist":"深水埗區", "earea":"Yau Yat Tsuen", "carea":"又一村"},
  "F25": { "edist":"Sham Shui Po District", "cdist":"深水埗區", "earea":"Nam Shan, Tai Hang Tung & Tai Hang Sai", "carea":"南山、大坑東及大坑西"},
  "G01": { "edist":"Kowloon City District", "cdist":"九龍城區", "earea":"Ma Tau Wai", "carea":"馬頭圍"},
  "G02": { "edist":"Kowloon City District", "cdist":"九龍城區", "earea":"Sung Wong Toi", "carea":"宋皇臺"},
  "G03": { "edist":"Kowloon City District", "cdist":"九龍城區", "earea":"Ma Hang Chung", "carea":"馬坑涌"},
  "G04": { "edist":"Kowloon City District", "cdist":"九龍城區", "earea":"Ma Tau Kok", "carea":"馬頭角"},
  "G05": { "edist":"Kowloon City District", "cdist":"九龍城區", "earea":"Lok Man", "carea":"樂民"},
  "G06": { "edist":"Kowloon City District", "cdist":"九龍城區", "earea":"Sheung Lok", "carea":"常樂"},
  "G07": { "edist":"Kowloon City District", "cdist":"九龍城區", "earea":"Ho Man Tin", "carea":"何文田"},
  "G08": { "edist":"Kowloon City District", "cdist":"九龍城區", "earea":"Kadoorie", "carea":"嘉道理"},
  "G09": { "edist":"Kowloon City District", "cdist":"九龍城區", "earea":"Prince", "carea":"太子"},
  "G10": { "edist":"Kowloon City District", "cdist":"九龍城區", "earea":"Kowloon Tong", "carea":"九龍塘"},
  "G11": { "edist":"Kowloon City District", "cdist":"九龍城區", "earea":"Lung Shing", "carea":"龍城"},
  "G12": { "edist":"Kowloon City District", "cdist":"九龍城區", "earea":"Kai Tak North", "carea":"啟德北"},
  "G13": { "edist":"Kowloon City District", "cdist":"九龍城區", "earea":"Kai Tak East", "carea":"啟德東"},
  "G14": { "edist":"Kowloon City District", "cdist":"九龍城區", "earea":"Kai Tak Central & South", "carea":"啟德中及南"},
  "G15": { "edist":"Kowloon City District", "cdist":"九龍城區", "earea":"Hoi Sham", "carea":"海心"},
  "G16": { "edist":"Kowloon City District", "cdist":"九龍城區", "earea":"To Kwa Wan North", "carea":"土瓜灣北"},
  "G17": { "edist":"Kowloon City District", "cdist":"九龍城區", "earea":"To Kwa Wan South", "carea":"土瓜灣南"},
  "G18": { "edist":"Kowloon City District", "cdist":"九龍城區", "earea":"Hok Yuen Laguna Verde", "carea":"鶴園海逸"},
  "G19": { "edist":"Kowloon City District", "cdist":"九龍城區", "earea":"Whampoa East", "carea":"黃埔東"},
  "G20": { "edist":"Kowloon City District", "cdist":"九龍城區", "earea":"Whampoa West", "carea":"黃埔西"},
  "G21": { "edist":"Kowloon City District", "cdist":"九龍城區", "earea":"Hung Hom Bay", "carea":"紅磡灣"},
  "G22": { "edist":"Kowloon City District", "cdist":"九龍城區", "earea":"Hung Hom", "carea":"紅磡"},
  "G23": { "edist":"Kowloon City District", "cdist":"九龍城區", "earea":"Ka Wai", "carea":"家維"},
  "G24": { "edist":"Kowloon City District", "cdist":"九龍城區", "earea":"Oi Man", "carea":"愛民"},
  "G25": { "edist":"Kowloon City District", "cdist":"九龍城區", "earea":"Oi Chun", "carea":"愛俊"},
  "H01": { "edist":"Wong Tai Sin District", "cdist":"黃大仙區", "earea":"Lung Tsui", "carea":"龍趣"},
  "H02": { "edist":"Wong Tai Sin District", "cdist":"黃大仙區", "earea":"Lung Ha", "carea":"龍下"},
  "H03": { "edist":"Wong Tai Sin District", "cdist":"黃大仙區", "earea":"Lung Sheung", "carea":"龍上"},
  "H04": { "edist":"Wong Tai Sin District", "cdist":"黃大仙區", "earea":"Fung Wong", "carea":"鳳凰"},
  "H05": { "edist":"Wong Tai Sin District", "cdist":"黃大仙區", "earea":"Fung Tak", "carea":"鳳德"},
  "H06": { "edist":"Wong Tai Sin District", "cdist":"黃大仙區", "earea":"Lung Sing", "carea":"龍星"},
  "H07": { "edist":"Wong Tai Sin District", "cdist":"黃大仙區", "earea":"San Po Kong", "carea":"新蒲崗"},
  "H08": { "edist":"Wong Tai Sin District", "cdist":"黃大仙區", "earea":"Tung Tau", "carea":"東頭"},
  "H09": { "edist":"Wong Tai Sin District", "cdist":"黃大仙區", "earea":"Tung Mei", "carea":"東美"},
  "H10": { "edist":"Wong Tai Sin District", "cdist":"黃大仙區", "earea":"Lok Fu", "carea":"樂富"},
  "H11": { "edist":"Wong Tai Sin District", "cdist":"黃大仙區", "earea":"Wang Tau Hom", "carea":"橫頭磡"},
  "H12": { "edist":"Wong Tai Sin District", "cdist":"黃大仙區", "earea":"Tin Keung", "carea":"天強"},
  "H13": { "edist":"Wong Tai Sin District", "cdist":"黃大仙區", "earea":"Tsui Chuk & Pang Ching", "carea":"翠竹及鵬程"},
  "H14": { "edist":"Wong Tai Sin District", "cdist":"黃大仙區", "earea":"Chuk Yuen South", "carea":"竹園南"},
  "H15": { "edist":"Wong Tai Sin District", "cdist":"黃大仙區", "earea":"Chuk Yuen North", "carea":"竹園北"},
  "H16": { "edist":"Wong Tai Sin District", "cdist":"黃大仙區", "earea":"Tsz Wan West", "carea":"慈雲西"},
  "H17": { "edist":"Wong Tai Sin District", "cdist":"黃大仙區", "earea":"Ching Oi", "carea":"正愛"},
  "H18": { "edist":"Wong Tai Sin District", "cdist":"黃大仙區", "earea":"Ching On", "carea":"正安"},
  "H19": { "edist":"Wong Tai Sin District", "cdist":"黃大仙區", "earea":"Tsz Wan East", "carea":"慈雲東"},
  "H20": { "edist":"Wong Tai Sin District", "cdist":"黃大仙區", "earea":"King Fu", "carea":"瓊富"},
  "H21": { "edist":"Wong Tai Sin District", "cdist":"黃大仙區", "earea":"Choi Wan East", "carea":"彩雲東"},
  "H22": { "edist":"Wong Tai Sin District", "cdist":"黃大仙區", "earea":"Choi Wan South", "carea":"彩雲南"},
  "H23": { "edist":"Wong Tai Sin District", "cdist":"黃大仙區", "earea":"Choi Wan West", "carea":"彩雲西"},
  "H24": { "edist":"Wong Tai Sin District", "cdist":"黃大仙區", "earea":"Chi Choi", "carea":"池彩"},
  "H25": { "edist":"Wong Tai Sin District", "cdist":"黃大仙區", "earea":"Choi Hung", "carea":"彩虹"},
  "J01": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Kwun Tong Central", "carea":"觀塘中心"},
  "J02": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Kowloon Bay", "carea":"九龍灣"},
  "J03": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Kai Yip", "carea":"啟業"},
  "J04": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Lai Ching", "carea":"麗晶"},
  "J05": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Ping Shek", "carea":"坪石"},
  "J06": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Choi Tak", "carea":"彩德"},
  "J07": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Jordan Valley", "carea":"佐敦谷"},
  "J08": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Shun Tin", "carea":"順天"},
  "J09": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Sheung Shun", "carea":"雙順"},
  "J10": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"On Lee", "carea":"安利"},
  "J11": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Kwun Tong On Tai", "carea":"觀塘安泰"},
  "J12": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Sau Mau Ping North", "carea":"秀茂坪å"},
  "J13": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Sau Mau Ping Central", "carea":"秀茂坪中"},
  "J14": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"On Tat", "carea":"安達"},
  "J15": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Sau Mau Ping South", "carea":"秀茂坪南"},
  "J16": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Po Tat", "carea":"寶達"},
  "J17": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Kwong Tak", "carea":"廣德"},
  "J18": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Hing Tin", "carea":"興田"},
  "J19": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Lam Tin", "carea":"藍田"},
  "J20": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Ping Tin", "carea":"平田"},
  "J21": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Pak Nga", "carea":"栢雅"},
  "J22": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Chun Cheung", "carea":"俊翔"},
  "J23": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Yau Tong East", "carea":"油塘東"},
  "J24": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Yau Chui", "carea":"油翠"},
  "J25": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Yau Lai", "carea":"油麗"},
  "J26": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Yau Tong West", "carea":"油塘西"},
  "J27": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Laguna City", "carea":"麗港城"},
  "J28": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"King Tin", "carea":"景田"},
  "J29": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Tsui Ping", "carea":"翠屏"},
  "J30": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Hiu Lai", "carea":"曉麗"},
  "J31": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Po Lok", "carea":"寶樂"},
  "J32": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Yuet Wah", "carea":"月華"},
  "J33": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Hip Hong", "carea":"協康"},
  "J34": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Lok Wah South", "carea":"樂華南"},
  "J35": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Lok Wah North", "carea":"樂華北"},
  "J36": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Hong Lok", "carea":"康樂"},
  "J37": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Ting On", "carea":"定安"},
  "J38": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Upper Ngau Tau Kok Estate", "carea":"牛頭角上邨"},
  "J39": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"Lower Ngau Tau Kok Estate", "carea":"牛頭角下邨"},
  "J40": { "edist":"Kwun Tong District", "cdist":"觀塘區", "earea":"To Tai", "carea":"淘大"},
  "K01": { "edist":"Tsuen Wan District", "cdist":"荃灣區", "earea":"Tak Wah", "carea":"德華"},
  "K02": { "edist":"Tsuen Wan District", "cdist":"荃灣區", "earea":"Yeung Uk Road", "carea":"楊屋道"},
  "K03": { "edist":"Tsuen Wan District", "cdist":"荃灣區", "earea":"Tsuen Wan South", "carea":"荃灣南"},
  "K04": { "edist":"Tsuen Wan District", "cdist":"荃灣區", "earea":"Hoi Bun", "carea":"海濱"},
  "K05": { "edist":"Tsuen Wan District", "cdist":"荃灣區", "earea":"Tsuen Wan West", "carea":"荃灣西"},
  "K06": { "edist":"Tsuen Wan District", "cdist":"荃灣區", "earea":"Clague Garden", "carea":"祈德尊"},
  "K07": { "edist":"Tsuen Wan District", "cdist":"荃灣區", "earea":"Tsuen Wan Centre", "carea":"荃灣中心"},
  "K08": { "edist":"Tsuen Wan District", "cdist":"荃灣區", "earea":"Discovery Park", "carea":"愉景"},
  "K09": { "edist":"Tsuen Wan District", "cdist":"荃灣區", "earea":"Fuk Loi", "carea":"福來"},
  "K10": { "edist":"Tsuen Wan District", "cdist":"荃灣區", "earea":"Luk Yeung", "carea":"綠楊"},
  "K11": { "edist":"Tsuen Wan District", "cdist":"荃灣區", "earea":"Ma Wan", "carea":"馬灣"},
  "K12": { "edist":"Tsuen Wan District", "cdist":"荃灣區", "earea":"Tsuen Wan Rural", "carea":"荃灣郊區"},
  "K13": { "edist":"Tsuen Wan District", "cdist":"荃灣區", "earea":"Ting Sham", "carea":"汀深"},
  "K14": { "edist":"Tsuen Wan District", "cdist":"荃灣區", "earea":"Lai To", "carea":"麗濤"},
  "K15": { "edist":"Tsuen Wan District", "cdist":"荃灣區", "earea":"Allway", "carea":"荃威"},
  "K16": { "edist":"Tsuen Wan District", "cdist":"荃灣區", "earea":"Cheung Shek", "carea":"象石"},
  "K17": { "edist":"Tsuen Wan District", "cdist":"荃灣區", "earea":"Shek Wai Kok", "carea":"石圍角"},
  "K18": { "edist":"Tsuen Wan District", "cdist":"荃灣區", "earea":"Lei Muk Shue West", "carea":"梨木樹西"},
  "K19": { "edist":"Tsuen Wan District", "cdist":"荃灣區", "earea":"Lei Muk Shue East", "carea":"梨木樹東"},
  "L01": { "edist":"Tuen Mun District", "cdist":"屯門區", "earea":"Tuen Mun Town Centre", "carea":"屯門市中心"},
  "L02": { "edist":"Tuen Mun District", "cdist":"屯門區", "earea":"Siu Chi", "carea":"兆置"},
  "L03": { "edist":"Tuen Mun District", "cdist":"屯門區", "earea":"On Ting", "carea":"安定"},
  "L04": { "edist":"Tuen Mun District", "cdist":"屯門區", "earea":"Siu Tsui", "carea":"兆翠"},
  "L05": { "edist":"Tuen Mun District", "cdist":"屯門區", "earea":"Yau Oi South", "carea":"友愛南"},
  "L06": { "edist":"Tuen Mun District", "cdist":"屯門區", "earea":"Yau Oi North", "carea":"友愛北"},
  "L07": { "edist":"Tuen Mun District", "cdist":"屯門區", "earea":"Tsui Hing", "carea":"翠興"},
  "L08": { "edist":"Tuen Mun District", "cdist":"屯門區", "earea":"Shan King", "carea":"山景"},
  "L09": { "edist":"Tuen Mun District", "cdist":"屯門區", "earea":"King Hing", "carea":"景興"},
  "L10": { "edist":"Tuen Mun District", "cdist":"屯門區", "earea":"Hing Tsak", "carea":"興澤"},
  "L11": { "edist":"Tuen Mun District", "cdist":"屯門區", "earea":"San Hui", "carea":"新墟"},
  "L12": { "edist":"Tuen Mun District", "cdist":"屯門區", "earea":"So Kwun Wat", "carea":"掃管笏"},
  "L13": { "edist":"Tuen Mun District", "cdist":"屯門區", "earea":"Sam Shing", "carea":"三聖"},
  "L14": { "edist":"Tuen Mun District", "cdist":"屯門區", "earea":"Hanford", "carea":"恒福"},
  "L15": { "edist":"Tuen Mun District", "cdist":"屯門區", "earea":"Yuet Wu", "carea":"悅湖"},
  "L16": { "edist":"Tuen Mun District", "cdist":"屯門區", "earea":"Siu Hei", "carea":"兆禧"},
  "L17": { "edist":"Tuen Mun District", "cdist":"屯門區", "earea":"Wu King", "carea":"湖景"},
  "L18": { "edist":"Tuen Mun District", "cdist":"屯門區", "earea":"Butterfly", "carea":"蝴蝶"},
  "L19": { "edist":"Tuen Mun District", "cdist":"屯門區", "earea":"Fu Sun", "carea":"富新"},
  "L20": { "edist":"Tuen Mun District", "cdist":"屯門區", "earea":"Lok Tsui", "carea":"樂翠"},
  "L21": { "edist":"Tuen Mun District", "cdist":"屯門區", "earea":"Lung Mun", "carea":"龍門"},
  "L22": { "edist":"Tuen Mun District", "cdist":"屯門區", "earea":"San King", "carea":"新景"},
  "L23": { "edist":"Tuen Mun District", "cdist":"屯門區", "earea":"Leung King", "carea":"良景"},
  "L24": { "edist":"Tuen Mun District", "cdist":"屯門區", "earea":"Tin King", "carea":"田景"},
  "L25": { "edist":"Tuen Mun District", "cdist":"屯門區", "earea":"Po Tin", "carea":"寶田"},
  "L26": { "edist":"Tuen Mun District", "cdist":"屯門區", "earea":"Kin Sang", "carea":"建生"},
  "L27": { "edist":"Tuen Mun District", "cdist":"屯門區", "earea":"Siu Hong", "carea":"兆康"},
  "L28": { "edist":"Tuen Mun District", "cdist":"屯門區", "earea":"Yan Tin", "carea":"欣田"},
  "L29": { "edist":"Tuen Mun District", "cdist":"屯門區", "earea":"Tuen Mun Rural", "carea":"屯門鄉郊"},
  "L30": { "edist":"Tuen Mun District", "cdist":"屯門區", "earea":"Fu Tai", "carea":"富泰"},
  "L31": { "edist":"Tuen Mun District", "cdist":"屯門區", "earea":"Prime View", "carea":"景峰"},
  "M01": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Fung Nin", "carea":"豐年"},
  "M02": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Yuen Long Centre", "carea":"元朗中心"},
  "M03": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Fung Cheung", "carea":"鳳翔"},
  "M04": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Yuen Lung", "carea":"元龍"},
  "M05": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Shap Pat Heung Central", "carea":"十八鄉中"},
  "M06": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Shui Pin", "carea":"水邊"},
  "M07": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Nam Ping", "carea":"南屏"},
  "M08": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Pek Long", "carea":"北朗"},
  "M09": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Yuen Long Tung Tau", "carea":"元朗東頭"},
  "M10": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Shap Pat Heung North", "carea":"十八鄉北"},
  "M11": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Shap Pat Heung East", "carea":"十八鄉東"},
  "M12": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Shap Pat Heung West", "carea":"十八鄉西"},
  "M13": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Ping Shan South", "carea":"屏山南"},
  "M14": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Hung Fuk", "carea":"洪福"},
  "M15": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Ha Tsuen", "carea":"廈村"},
  "M16": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Ping Shan Central", "carea":"屏山中"},
  "M17": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Shing Yan", "carea":"盛欣"},
  "M18": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Tin Shing", "carea":"天盛"},
  "M19": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Tin Yiu", "carea":"天耀"},
  "M20": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Yiu Yau", "carea":"耀祐"},
  "M21": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Tsz Yau", "carea":"慈祐"},
  "M22": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Kingswood South", "carea":"嘉湖南"},
  "M23": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Shui Oi", "carea":"瑞愛"},
  "M24": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Shui Wah", "carea":"瑞華"},
  "M25": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Chung Wah", "carea":"頌華"},
  "M26": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Chung Pak", "carea":"頌栢"},
  "M27": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Kingswood North", "carea":"嘉湖北"},
  "M28": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Yuet Yan", "carea":"悅恩"},
  "M29": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Ching King", "carea":"晴景"},
  "M30": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Fu Yan", "carea":"富恩"},
  "M31": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Yat Chak", "carea":"逸澤"},
  "M32": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Tin Heng", "carea":"天恒"},
  "M33": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Wang Yat", "carea":"宏逸"},
  "M34": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Ping Shan North", "carea":"屏山北"},
  "M35": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Fairview Park", "carea":"錦綉花園"},
  "M36": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"San Tin", "carea":"新田"},
  "M37": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Kam Tin", "carea":"錦田"},
  "M38": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Pat Heung North", "carea":"八鄉北"},
  "M39": { "edist":"Yuen Long District", "cdist":"元朗區", "earea":"Pat Heung South", "carea":"八鄉南"},
  "N01": { "edist":"North District", "cdist":"北區", "earea":"Luen Wo Hui", "carea":"聯和墟"},
  "N02": { "edist":"North District", "cdist":"北區", "earea":"Fanling Town", "carea":"粉嶺市"},
  "N03": { "edist":"North District", "cdist":"北區", "earea":"Cheung Wah", "carea":"祥華"},
  "N04": { "edist":"North District", "cdist":"北區", "earea":"Wah Do", "carea":"華都"},
  "N05": { "edist":"North District", "cdist":"北區", "earea":"Wah Ming", "carea":"華明"},
  "N06": { "edist":"North District", "cdist":"北區", "earea":"Yan Shing", "carea":"欣盛"},
  "N07": { "edist":"North District", "cdist":"北區", "earea":"Fanling South", "carea":"粉嶺南"},
  "N08": { "edist":"North District", "cdist":"北區", "earea":"Shing Fuk", "carea":"盛福"},
  "N09": { "edist":"North District", "cdist":"北區", "earea":"Ching Ho", "carea":"清河"},
  "N10": { "edist":"North District", "cdist":"北區", "earea":"Yu Tai", "carea":"御太"},
  "N11": { "edist":"North District", "cdist":"北區", "earea":"Sheung Shui Rural", "carea":"上水鄉郊"},
  "N12": { "edist":"North District", "cdist":"北區", "earea":"Choi Yuen", "carea":"彩園"},
  "N13": { "edist":"North District", "cdist":"北區", "earea":"Shek Wu Hui", "carea":"石湖墟"},
  "N14": { "edist":"North District", "cdist":"北區", "earea":"Tin Ping West", "carea":"天平西"},
  "N15": { "edist":"North District", "cdist":"北區", "earea":"Fung Tsui", "carea":"鳳翠"},
  "N16": { "edist":"North District", "cdist":"北區", "earea":"Sha Ta", "carea":"沙打"},
  "N17": { "edist":"North District", "cdist":"北區", "earea":"Tin Ping East", "carea":"天平東"},
  "N18": { "edist":"North District", "cdist":"北區", "earea":"Queen's Hill", "carea":"皇后山"},
  "P01": { "edist":"Tai Po District", "cdist":"大埔區", "earea":"Tai Po Hui", "carea":"大埔墟"},
  "P02": { "edist":"Tai Po District", "cdist":"大埔區", "earea":"Chung Ting", "carea":"頌汀"},
  "P03": { "edist":"Tai Po District", "cdist":"大埔區", "earea":"Tai Po Central", "carea":"大埔中"},
  "P04": { "edist":"Tai Po District", "cdist":"大埔區", "earea":"Tai Yuen", "carea":"大元"},
  "P05": { "edist":"Tai Po District", "cdist":"大埔區", "earea":"Fu Heng", "carea":"富亨"},
  "P06": { "edist":"Tai Po District", "cdist":"大埔區", "earea":"Yee Fu", "carea":"怡富"},
  "P07": { "edist":"Tai Po District", "cdist":"大埔區", "earea":"Fu Ming Sun", "carea":"富明新"},
  "P08": { "edist":"Tai Po District", "cdist":"大埔區", "earea":"Kwong Fuk & Plover Cove", "carea":"廣福及寶湖"},
  "P09": { "edist":"Tai Po District", "cdist":"大埔區", "earea":"Wang Fuk", "carea":"宏福"},
  "P10": { "edist":"Tai Po District", "cdist":"大埔區", "earea":"Tai Po Kau", "carea":"大埔滘"},
  "P11": { "edist":"Tai Po District", "cdist":"大埔區", "earea":"Wan Tau Tong", "carea":"運頭塘"},
  "P12": { "edist":"Tai Po District", "cdist":"大埔區", "earea":"San Fu", "carea":"新富"},
  "P13": { "edist":"Tai Po District", "cdist":"大埔區", "earea":"Lam Tsuen Valley", "carea":"林æ谷"},
  "P14": { "edist":"Tai Po District", "cdist":"大埔區", "earea":"Po Nga", "carea":"寶雅"},
  "P15": { "edist":"Tai Po District", "cdist":"大埔區", "earea":"Tai Wo", "carea":"太和"},
  "P16": { "edist":"Tai Po District", "cdist":"大埔區", "earea":"Old Market & Serenity", "carea":"舊墟及太湖"},
  "P17": { "edist":"Tai Po District", "cdist":"大埔區", "earea":"Hong Lok Yuen", "carea":"康樂園"},
  "P18": { "edist":"Tai Po District", "cdist":"大埔區", "earea":"Shuen Wan", "carea":"船灣"},
  "P19": { "edist":"Tai Po District", "cdist":"大埔區", "earea":"Sai Kung North", "carea":"西貢北"},
  "Q01": { "edist":"Sai Kung District", "cdist":"西貢區", "earea":"Sai Kung Central", "carea":"西貢市中心"},
  "Q02": { "edist":"Sai Kung District", "cdist":"西貢區", "earea":"Pak Sha Wan", "carea":"白沙灣"},
  "Q03": { "edist":"Sai Kung District", "cdist":"西貢區", "earea":"Sai Kung Islands", "carea":"西貢離島"},
  "Q04": { "edist":"Sai Kung District", "cdist":"西貢區", "earea":"Hang Hau East", "carea":"坑口東"},
  "Q05": { "edist":"Sai Kung District", "cdist":"西貢區", "earea":"Hang Hau West", "carea":"坑口西"},
  "Q06": { "edist":"Sai Kung District", "cdist":"西貢區", "earea":"Choi Kin", "carea":"彩健"},
  "Q07": { "edist":"Sai Kung District", "cdist":"西貢區", "earea":"Kin Ming", "carea":"健明"},
  "Q08": { "edist":"Sai Kung District", "cdist":"西貢區", "earea":"Do Shin", "carea":"都善"},
  "Q09": { "edist":"Sai Kung District", "cdist":"西貢區", "earea":"Wai King", "carea":"維景"},
  "Q10": { "edist":"Sai Kung District", "cdist":"西貢區", "earea":"Hoi Chun", "carea":"海晉"},
  "Q11": { "edist":"Sai Kung District", "cdist":"西貢區", "earea":"Po Yee", "carea":"寶怡"},
  "Q12": { "edist":"Sai Kung District", "cdist":"西貢區", "earea":"Fu Kwan", "carea":"富君"},
  "Q13": { "edist":"Sai Kung District", "cdist":"西貢區", "earea":"O Tong", "carea":"澳唐"},
  "Q14": { "edist":"Sai Kung District", "cdist":"西貢區", "earea":"Sheung Tak", "carea":"尚德"},
  "Q15": { "edist":"Sai Kung District", "cdist":"西貢區", "earea":"Kwong Ming", "carea":"廣明"},
  "Q16": { "edist":"Sai Kung District", "cdist":"西貢區", "earea":"Hong King", "carea":"康景"},
  "Q17": { "edist":"Sai Kung District", "cdist":"西貢區", "earea":"Tsui Lam", "carea":"翠林"},
  "Q18": { "edist":"Sai Kung District", "cdist":"西貢區", "earea":"Po Lam", "carea":"寶林"},
  "Q19": { "edist":"Sai Kung District", "cdist":"西貢區", "earea":"Yan Ying", "carea":"欣英"},
  "Q20": { "edist":"Sai Kung District", "cdist":"西貢區", "earea":"Wai Yan", "carea":"慧茵"},
  "Q21": { "edist":"Sai Kung District", "cdist":"西貢區", "earea":"Wan Hang", "carea":"運亨"},
  "Q22": { "edist":"Sai Kung District", "cdist":"西貢區", "earea":"King Lam", "carea":"景林"},
  "Q23": { "edist":"Sai Kung District", "cdist":"西貢區", "earea":"Hau Tak", "carea":"厚德"},
  "Q24": { "edist":"Sai Kung District", "cdist":"西貢區", "earea":"Fu Nam", "carea":"富藍"},
  "Q25": { "edist":"Sai Kung District", "cdist":"西貢區", "earea":"Tak Ming", "carea":"德明"},
  "Q26": { "edist":"Sai Kung District", "cdist":"西貢區", "earea":"Nam On", "carea":"南安"},
  "Q27": { "edist":"Sai Kung District", "cdist":"西貢區", "earea":"Kwan Po", "carea":"軍寶"},
  "Q28": { "edist":"Sai Kung District", "cdist":"西貢區", "earea":"Wan Po North", "carea":"環保北"},
  "Q29": { "edist":"Sai Kung District", "cdist":"西貢區", "earea":"Wan Po South", "carea":"環保南"},
  "R01": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Sha Tin Town Centre", "carea":"沙田市中心"},
  "R02": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Lek Yuen", "carea":"瀝源"},
  "R03": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Wo Che Estate", "carea":"禾輋邨"},
  "R04": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"City One", "carea":"第一城"},
  "R05": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Yue Shing", "carea":"愉城"},
  "R06": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Wong Uk", "carea":"王屋"},
  "R07": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Sha Kok", "carea":"沙角"},
  "R08": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Pok Hong", "carea":"博康"},
  "R09": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Shui Chuen O", "carea":"水泉澳"},
  "R10": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Jat Chuen", "carea":"乙泉"},
  "R11": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Chun Fung", "carea":"秦豐"},
  "R12": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Sun Tin Wai", "carea":"新田圍"},
  "R13": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Chui Tin", "carea":"翠田"},
  "R14": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Hin Ka", "carea":"顯嘉"},
  "R15": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Lower Shing Mun", "carea":"下城門"},
  "R16": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Wan Shing", "carea":"雲城"},
  "R17": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Keng Hau", "carea":"徑口"},
  "R18": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Tin Sum", "carea":"田心"},
  "R19": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Chui Ka", "carea":"翠嘉"},
  "R20": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Tai Wai", "carea":"大圍"},
  "R21": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Chung Tin", "carea":"松田"},
  "R22": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Sui Wo", "carea":"穗禾"},
  "R23": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Fo Tan", "carea":"火炭"},
  "R24": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Chun Ma", "carea":"駿馬"},
  "R25": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Hoi Nam", "carea":"海嵐"},
  "R26": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Chung On", "carea":"頌安"},
  "R27": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Kam To", "carea":"錦濤"},
  "R28": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Ma On Shan Town Centre", "carea":"馬鞍山市中心"},
  "R29": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Wu Kai Sha", "carea":"烏溪沙"},
  "R30": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Lee On", "carea":"利安"},
  "R31": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Fu Lung", "carea":"富龍"},
  "R32": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Kam Ying", "carea":"錦英"},
  "R33": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Yiu On", "carea":"耀安"},
  "R34": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Heng On", "carea":"恆安"},
  "R35": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Tai Shui Hang", "carea":"大水坑"},
  "R36": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"On Tai", "carea":"鞍泰"},
  "R37": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Yu Yan", "carea":"愉欣"},
  "R38": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Di Yee", "carea":"帝怡"},
  "R39": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Bik Woo", "carea":"碧湖"},
  "R40": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Kwong Hong", "carea":"廣康"},
  "R41": { "edist":"Sha Tin District", "cdist":"沙田區", "earea":"Kwong Yuen", "carea":"廣源"},
  "S01": { "edist":"Kwai Tsing District", "cdist":"葵青區", "earea":"Kwai Hing", "carea":"葵興"},
  "S02": { "edist":"Kwai Tsing District", "cdist":"葵青區", "earea":"Kwai Luen", "carea":"葵聯"},
  "S03": { "edist":"Kwai Tsing District", "cdist":"葵青區", "earea":"Kwai Shing East Estate", "carea":"葵盛東邨"},
  "S04": { "edist":"Kwai Tsing District", "cdist":"葵青區", "earea":"Upper Tai Wo Hau", "carea":"上大窩口"},
  "S05": { "edist":"Kwai Tsing District", "cdist":"葵青區", "earea":"Lower Tai Wo Hau", "carea":"下大窩口"},
  "S06": { "edist":"Kwai Tsing District", "cdist":"葵青區", "earea":"Kwai Chung Estate South", "carea":"葵涌邨南"},
  "S07": { "edist":"Kwai Tsing District", "cdist":"葵青區", "earea":"Kwai Chung Estate North", "carea":"葵涌邨北"},
  "S08": { "edist":"Kwai Tsing District", "cdist":"葵青區", "earea":"Shek Yam", "carea":"石蔭"},
  "S09": { "edist":"Kwai Tsing District", "cdist":"葵青區", "earea":"Tai Pak Tin West", "carea":"大白田西"},
  "S10": { "edist":"Kwai Tsing District", "cdist":"葵青區", "earea":"Tai Pak Tin East", "carea":"大白田東"},
  "S11": { "edist":"Kwai Tsing District", "cdist":"葵青區", "earea":"On Yam", "carea":"安蔭"},
  "S12": { "edist":"Kwai Tsing District", "cdist":"葵青區", "earea":"Shek Lei North", "carea":"石籬北"},
  "S13": { "edist":"Kwai Tsing District", "cdist":"葵青區", "earea":"Shek Lei South", "carea":"石籬南"},
  "S14": { "edist":"Kwai Tsing District", "cdist":"葵青區", "earea":"Kwai Fong", "carea":"葵芳"},
  "S15": { "edist":"Kwai Tsing District", "cdist":"葵青區", "earea":"Hing Fong", "carea":"興芳"},
  "S16": { "edist":"Kwai Tsing District", "cdist":"葵青區", "earea":"Wah Lai", "carea":"華麗"},
  "S17": { "edist":"Kwai Tsing District", "cdist":"葵青區", "earea":"Lai Wah", "carea":"荔華"},
  "S18": { "edist":"Kwai Tsing District", "cdist":"葵青區", "earea":"Cho Yiu", "carea":"祖堯"},
  "S19": { "edist":"Kwai Tsing District", "cdist":"葵青區", "earea":"Lai King", "carea":"荔景"},
  "S20": { "edist":"Kwai Tsing District", "cdist":"葵青區", "earea":"Kwai Shing West Estate", "carea":"葵盛西邨"},
  "S21": { "edist":"Kwai Tsing District", "cdist":"葵青區", "earea":"On Ho", "carea":"安灝"},
  "S22": { "edist":"Kwai Tsing District", "cdist":"葵青區", "earea":"Wai Ying", "carea":"偉盈"},
  "S23": { "edist":"Kwai Tsing District", "cdist":"葵青區", "earea":"Tsing Yi Estate", "carea":"é衣邨"},
  "S24": { "edist":"Kwai Tsing District", "cdist":"葵青區", "earea":"Greenfield", "carea":"翠怡"},
  "S25": { "edist":"Kwai Tsing District", "cdist":"葵青區", "earea":"Cheung Ching", "carea":"長青"},
  "S26": { "edist":"Kwai Tsing District", "cdist":"葵青區", "earea":"Cheung Hong", "carea":"長康"},
  "S27": { "edist":"Kwai Tsing District", "cdist":"葵青區", "earea":"Shing Hong", "carea":"盛康"},
  "S28": { "edist":"Kwai Tsing District", "cdist":"葵青區", "earea":"Tsing Yi South", "carea":"青衣南"},
  "S29": { "edist":"Kwai Tsing District", "cdist":"葵青區", "earea":"Cheung Hang", "carea":"長亨"},
  "S30": { "edist":"Kwai Tsing District", "cdist":"葵青區", "earea":"Ching Fat", "carea":"青發"},
  "S31": { "edist":"Kwai Tsing District", "cdist":"葵青區", "earea":"Cheung On", "carea":"長安"},
  "T01": { "edist":"Islands District", "cdist":"離島區", "earea":"Lantau", "carea":"大嶼山"},
  "T02": { "edist":"Islands District", "cdist":"離島區", "earea":"Mun Yat", "carea":"滿逸"},
  "T03": { "edist":"Islands District", "cdist":"離島區", "earea":"Yat Tung Estate North", "carea":"逸東邨北"},
  "T04": { "edist":"Islands District", "cdist":"離島區", "earea":"Tung Chung South", "carea":"東涌南"},
  "T05": { "edist":"Islands District", "cdist":"離島區", "earea":"Tung Chung Central", "carea":"東涌中"},
  "T06": { "edist":"Islands District", "cdist":"離島區", "earea":"Tung Chung North", "carea":"東涌北"},
  "T07": { "edist":"Islands District", "cdist":"離島區", "earea":"Discovery Bay", "carea":"愉景灣"},
  "T08": { "edist":"Islands District", "cdist":"離島區", "earea":"Peng Chau & Hei Ling Chau", "carea":"坪洲及喜靈洲"},
  "T09": { "edist":"Islands District", "cdist":"離島區", "earea":"Lamma & Po Toi", "carea":"南丫及蒲台"},
  "T10": { "edist":"Islands District", "cdist":"離島區", "earea":"Cheung Chau", "carea":"長洲"}
}


def geojson(result):
    properties = {
        "label": str(result),
    }
    if result._scores:
        properties["score"] = result.score
    for key in result.keys:
        val = getattr(result, key, None)
        if val and key not in ['lat', 'lon', '_id']:
            properties[key] = val
    type_ = result._doc.get('type')
    if type_ and type_ not in properties:
        properties[type_] = properties.get('name')
    housenumber = getattr(result, 'housenumber', None)
    if housenumber:
        if result.lang == 'zh':
            properties['name'] = '{}{}號'.format(properties.get('name'),
                                                housenumber)
        else:
            properties['name'] = '{} {}'.format(housenumber,
                                                properties.get('name'))
    try:
        properties['distance'] = int(result.distance)
    except ValueError:
        pass

    try:
        resultType = 'h' if result.type == 'housenumber' else result.type.lower()
        properties['place_id'] = hashids.encode(int(properties['id'])) + '_' + geohash.encode(float(result.lat), float(result.lon), 12) + resultType
    except:
        properties['place_id'] = properties['id'] + '_' + geohash.encode(float(result.lat), float(result.lon), 12) + resultType

    try:
        properties['type'] = 'H' if result.type == 'housenumber' else result.type
    except:
        pass

    try:
        if result.lang == 'zh':
            properties['area'] = cacodeDict[result.cacode]['carea']
            properties['district'] = cacodeDict[result.cacode]['cdist']
        else:
            properties['area'] = cacodeDict[result.cacode]['earea']
            properties['district'] = cacodeDict[result.cacode]['edist']
    except:
        pass

    return {
        "type": "Feature",
        "geometry": {
            "type": "Point",
            "coordinates": [float(result.lon), float(result.lat)]
        },
        "properties": properties,
    }
